[theme]
# Cor dos detalhes (botões ativos, checkboxes, etc)
primaryColor = "#f39c12" 

# Fundo da área principal (Preto mais claro/Grafite)
backgroundColor = "#121212"

# Fundo da Sidebar e de widgets (Preto Sólido)
secondaryBackgroundColor = "#000000"

# Cor do texto
textColor = "#FFFFFF"

# Fonte profissional
font = "sans serif"